INSERT INTO books (
  isbn,
  title,
  authors,
  genres,
  publisher,
  publication_year,
  description,
  cover_image,
  total_copies,
  available_copies,
  formats,
  pages,
  "createdAt",
  "updatedAt"
) VALUES
('978-0316769488', 'Catcher in the Rye', ARRAY['J.D. Salinger'], ARRAY['Fiction','Coming-of-Age'], 'Little, Brown and Company', 1951, 'A novel about teenage rebellion and angst.', '/public/images/book-covers/catcher in the rye.jpg', 12, 6, ARRAY['Hardcover','Paperback'], 277, NOW(), NOW()),
('978-1400079988', 'War and Peace', ARRAY['Leo Tolstoy'], ARRAY['Historical Fiction','Classic'], 'The Russian Messenger', 1867, 'An epic novel about war, love, and Russian society.', '/public/images/book-covers/war and peace.jpg', 8, 6, ARRAY['Hardcover','Paperback','eBook'], 1225, NOW(), NOW()),
('978-1503290563', 'Pride and Prejudice', ARRAY['Jane Austen'], ARRAY['Romance','Classic'], 'T. Egerton', 1813, 'A classic romantic novel about manners, marriage, and misunderstandings.', '/public/images/book-covers/pride and prejudice.jpg', 14, 11, ARRAY['Hardcover','Paperback','eBook'], 432, NOW(), NOW()),
('978-0486415871', 'Crime and Punishment', ARRAY['Fyodor Dostoevsky'], ARRAY['Psychological Fiction','Philosophical'], 'Dover Publications', 1866, 'A psychological novel about guilt and redemption.', '/public/images/book-covers/crime and punishment.png', 15, 10, ARRAY['Hardcover','Paperback','eBook'], 671, NOW(), NOW()),
('978-0439023481', 'The Hunger Games', ARRAY['Suzanne Collins'], ARRAY['Dystopian','Science Fiction'], 'Scholastic Press', 2008, 'A dystopian novel about a brutal televised competition.', '/public/images/book-covers/hungry games.jpg', 25, 21, ARRAY['Hardcover','Paperback','eBook'], 374, NOW(), NOW()),
('978-1503280786', 'Moby Dick', ARRAY['Herman Melville'], ARRAY['Adventure','Classic'], 'Harper & Brothers', 1851, 'A seafaring adventure centered around a vengeful quest for a white whale.', '/public/images/book-covers/moby dick.png', 10, 7, ARRAY['Hardcover','Paperback','eBook'], 635, NOW(), NOW()),
('978-0743273565', 'The Great Gatsby', ARRAY['F. Scott Fitzgerald'], ARRAY['Classic','Tragedy'], 'Charles Scribner''s Sons', 1925, 'A tragic tale of wealth, love, and the American Dream.', '/public/images/book-covers/debe924f-fbb1-4a7e-964c-578da2e01332-gatsby.jpg', 12, 10, ARRAY['Hardcover','Paperback','eBook'], 180, NOW(), NOW()),
('978-0307474278', 'Da Vinci Code', ARRAY['Dan Brown'], ARRAY['Mystery','Thriller'], 'Doubleday', 2003, 'A thrilling novel involving symbology, secret societies, and historical conspiracies.', '/public/images/book-covers/da vinci code.jpg', 20, 14, ARRAY['Hardcover','Paperback','eBook','Audiobook'], 489, NOW(), NOW()),
('978-0765387561', 'The Invisible Life of Addie LaRue', ARRAY['V. E. Schwab'], ARRAY['Fantasy','Historical'], 'Tor Books', 2020, 'A young woman makes a Faustian bargain to live forever, but is cursed to be forgotten by everyone she meets—until someone remembers her name.', '/public/images/book-covers/bbeb83cf-c0fe-4466-9aaf-5ed1591779e1invisible.jpg', 5, 5, ARRAY['Hardcover','Softcover'], 448, NOW(), NOW()),
('978-0547928227', 'The Hobbit', ARRAY['J.R.R. Tolkien'], ARRAY['Fantasy','Adventure'], 'George Allen & Unwin', 1937, 'A fantasy adventure following Bilbo Baggins on his quest.', '/public/images/book-covers/the hobbit.png', 20, 18, ARRAY['Hardcover','Paperback','eBook','Audiobook'], 310, NOW(), NOW()),
('978-0451524935', '1984', ARRAY['George Orwell'], ARRAY['Dystopian','Political Fiction'], 'Signet Classics', 1949, 'A dystopian novel set in a totalitarian society ruled by Big Brother.', '/public/images/book-covers/9eca12e2-b640-4bd1-a17f-a67ad77343c6-1984.jpg', 10, 8, ARRAY['Hardcover','Paperback','eBook'], 328, NOW(), NOW()),
('978-0525536291', 'The Vanishing Half', ARRAY['Brit Bennett','her mother'], ARRAY['Historical Fiction','Literary'], 'Riverhead Books', 2020, 'Twin sisters—one Black, one passing for white—live vastly different lives, each reckoning with the weight of their past and identity.', '/public/images/book-covers/00f5ae7d-cdaf-4445-b8ec-371fc9f7a414-vanishing.jpg', 4, 4, ARRAY['Paperback','Softcover'], 4, NOW(), NOW()),
('978-0061120084', 'Mockingbird', ARRAY['Harper Lee'], ARRAY['Classic','Historical Fiction'], 'J.B. Lippincott & Co.', 1960, 'A novel dealing with racial injustice in the American South.', '/public/images/book-covers/mockingbird.png', 18, 14, ARRAY['Hardcover','Paperback','eBook','Audiobook'], 324, NOW(), NOW()),
(
  '0-7475-3269-9',
  'Harry Potter and the Philosopher''s Stone',
  ARRAY['J. K. Rowling'],
  ARRAY['Fantasy','Adventure','Children’s literature'],
  'Bloomsbury (UK); Scholastic (US)',
  1997,
  'Harry Potter, an orphan raised by his cruel aunt and uncle, discovers on his eleventh birthday that he’s the heir of a powerful wizarding legacy—and has been accepted to Hogwarts School of Witchcraft and Wizardry. Thrown into a world of magic, friendship, and danger, he makes two lifelong friends and uncovers the mystery of the Philosopher’s Stone, an object of immortality hidden within the school’s walls.',
  '/public/images/book-covers/c57b3d21-8d2c-47f8-913e-cb2d5284f605-harrypotter.jpg',
  3,
  3,
  ARRAY['Hardcover','Paperback'],
  223,
  '2025-06-08T07:39:59.212Z'::timestamptz,
  '2025-06-08T07:43:29.493Z'::timestamptz
);